### ISSUE TITLE
binary installation issue

### ISSUE THREAD

**Issue by shack2012** [TheHive-Project/CortexDocs#10]
Hi,
i'm trying to install Cortex on ubuntu (virtualBox), but when i lunch command  bin/cortex -Dconfig.file=/etc/cortex/application.conf getting this error: 

```
[info] a.e.s.Slf4jLogger - Slf4jLogger started
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Oops, cannot start the server.
Configuration error: Configuration error[
The application secret has not been set, and we are in prod mode. Your application is not secure.
```
tips to fix?
thanks

**Comment by Tribux** [comment]
Same issue with Docker installations

**Comment by shack2012** [comment]
I solved installing before elasticsearch

**Comment by cuongdinh** [comment]
I still have the issue even after installing elasticsearch. Please advise! Thanks!

**Comment by nadouani** [comment]
Well, you need to follow this step to add the secret for prod mode:

https://github.com/TheHive-Project/CortexDocs/blob/91d1e5c32901ac383e818e03c835bef440c242ba/admin/quick-start.md#step-1-setup-cortex
