### ISSUE TITLE
Clear Jobs History? 

### ISSUE THREAD

**Issue by mathurin68** [TheHive-Project/CortexDocs#18]
Maybe I've missed it somewhere but is there a way to clear the 'Jobs History' ?

**Comment by nadouani** [comment]
Hello, no, cortex UI doesn't allow this. If you want to clear the job history, you can remove the data from ES directly

**Comment by Lexati** [comment]
Clear jobs history Cortex
curl -sS --noproxy '*' 'http://localhost:9200/cortex_6/_delete_by_query' -d '{"query": {"match": {"relations" : "job"}}}' -XPOST -H 'Content-Type: application/json'
