### ISSUE TITLE
sorry there are no analyzers for the selected observables

### ISSUE THREAD

**Issue by robomotic** [TheHive-Project/CortexDocs#25]
So I have all configured from thehive and cortex to talk to each other. I then have enabled the VirusTotal_GetReport_3_0 analyser and tested with a md5 file hash in the cortex job panel which worked fined.

Now from thehive I create a new case and add the same ioc (different md5,sha1,sha256 hashes) but a popup message keeps saying "Sorry, there are currently no analyzers for the selected observable type(s)" which is obviously a bug of some sort.

I have checked the application log and I can see thehive authenticating with the cortex so it must be something in the communication logic?

Anyway to debug this?

**Comment by robomotic** [comment]
I alos noticed the cortex integration logo on the bottom right bar in the UI with version 3.1.2-1.

**Comment by robomotic** [comment]
I have also tried to run this script with the same API key just to make sure I can talk to cortex and seems to be working:

```
import json
import uuid

from cortex4py.api import Api
from cortex4py.query import *

api = Api('http://atlantis:9001', 'sameapikeyinthehive')

# Get enabled analyzers
analyzers = api.analyzers.find_all({}, range='all')

# Display enabled analyzers' names
for analyzer in analyzers:
  print('Analyzer {} is enabled'.format(analyzer.name))

```

**Comment by nadouani** [comment]
Hello, the instance name can contain hyphens, you probably had an authentication issue.
