### ISSUE TITLE
"Add Custom Field" not working in cortex responder 

### ISSUE THREAD

**Issue by AliJaafar47** [TheHive-Project/CortexDocs#41]
I'm trying to add a custom field to a case in the function operations but it's not working 
def operations(self, raw):
    return[self.build_operation("AddCustomField",name="ticket_gir",value=raw["numeroIncident"],tpe= "string")]

**Comment by mdavis332** [comment]
Just ran across this issue as well. Problem is that the method name is actually AddCustomFields (with an 's' on the end). I've opened PR #45 to update the docs, but devs could choose to adjust the multiple places in scala code where the method name is defined.

**Comment by nadouani** [comment]
Yes, @mdavis332 is right. We have updated the docs accordingly.
